### ISSUE TITLE
Incorrect number of bindings

### ISSUE THREAD

**Issue by ryanafolk** [juliema/aTRAM#204]
An error encountered in a large whole-genome dataset with lots of iterations after 9 completed:

aTRAM iteration 10
Blasting query against shards: iteration 10
Traceback (most recent call last):
  File "./aTRAM/atram.py", line 507, in <module>
    main(ARGS)
  File "./aTRAM/atram.py", line 41, in main
    atram_loop(args, db_conn, assembler, query, all_shards)
  File "./aTRAM/atram.py", line 64, in atram_loop
    if not db.sra_blast_hits_count(db_conn, iteration):
  File "/srv/gspeedq32/ryanfolk/new_atram2_oresitrophe_cp/aTRAM/lib/db.py", line 158, in sra_blast_hits_count
    result = db_conn.execute(sql, str(iteration))
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 2 supplied.

**Comment by juliema** [comment]
I think this error has to do with he fact that iteration 10 has two digits in it?  I got the same thing:

aTRAM iteration 10
Blasting query against shards: iteration 10
Traceback (most recent call last):
  File "../../../../atram_2.0/atram_2.0/aTRAM/atram.py", line 507, in <module>
    main(ARGS)
  File "../../../../atram_2.0/atram_2.0/aTRAM/atram.py", line 41, in main
    atram_loop(args, db_conn, assembler, query, all_shards)
  File "../../../../atram_2.0/atram_2.0/aTRAM/atram.py", line 64, in atram_loop
    if not db.sra_blast_hits_count(db_conn, iteration):
  File "/srv/gspeedq32/atram_2.0/atram_2.0/aTRAM/lib/db.py", line 158, in sra_blast_hits_count
    result = db_conn.execute(sql, str(iteration))
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 2 supplied.
