### ISSUE TITLE
atram.py error after BLAST update to version 2.7.11

### ISSUE THREAD

**Issue by kingcohn1** [juliema/aTRAM#210]
After creating a blast database using:
```bash
(venv) molecularecology@molecular-ecology:~/Desktop/atram/aTRAM_12_14/aTRAM$ python atram_preprocessor.py -c 4 -b CPB1_library/CPB1 --end-1 /home/molecularecology/Desktop/atram/CP1_R1_CLEAN.fq --end-2 /home/molecularecology/Desktop/atram/CP1_R2_CLEAN.fq
```
Which created a database but failed during the atram command:

```bash
2017-12-21 16:03:05 INFO: aTRAM blast DB = "/home/molecularecology/Desktop/atram/aTRAM_1/atram_2017-11-16", query = "/home/molecularecology/Desktop/atram/aTRAM_1/lepdec_OGSv1.1/lepdec_OGSv1.1_1.cd.fa", iteration 1
2017-12-21 16:03:05 INFO: Blasting query against shards: iteration 1
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "atram.py", line 198, in blast_query_against_one_shard
    db.insert_blast_hit_batch(db_conn, batch)
  File "/home/molecularecology/Desktop/atram/aTRAM_12_14/aTRAM/lib/db.py", line 175, in insert_blast_hit_batch
    db_conn.executemany(sql, batch)
sqlite3.OperationalError: no such table: aux.sra_blast_hits
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "atram.py", line 527, in <module>
    assemble(ARGS)
  File "atram.py", line 39, in assemble
    assembly_loop(assembler, blast_db, query)
  File "atram.py", line 54, in assembly_loop
    blast_query_against_all_shards(assembler)
  File "atram.py", line 147, in blast_query_against_all_shards
    _ = [result.get() for result in results]  # noqa
  File "atram.py", line 147, in <listcomp>
    _ = [result.get() for result in results]  # noqa
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
sqlite3.OperationalError: no such table: aux.sra_blast_hits
```
Similar issue with test data_2
```bash
(venv) molecularecology@molecular-ecology:~/Desktop/atram/aTRAM_12_14/aTRAM$ python atram.py -b testLib/tests -o tests2.atram -q Phum.PHUM003350-PA.pep.fasta
2017-12-21 16:30:15 INFO: aTRAM blast DB = "testLib/tests", query = "Phum.PHUM003350-PA.pep.fasta", iteration 1
2017-12-21 16:30:15 INFO: Blasting query against shards: iteration 1
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "atram.py", line 198, in blast_query_against_one_shard
    db.insert_blast_hit_batch(db_conn, batch)
  File "/home/molecularecology/Desktop/atram/aTRAM_12_14/aTRAM/lib/db.py", line 175, in insert_blast_hit_batch
    db_conn.executemany(sql, batch)
sqlite3.OperationalError: no such table: aux.sra_blast_hits
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "atram.py", line 527, in <module>
    assemble(ARGS)
  File "atram.py", line 39, in assemble
    assembly_loop(assembler, blast_db, query)
  File "atram.py", line 54, in assembly_loop
    blast_query_against_all_shards(assembler)
  File "atram.py", line 147, in blast_query_against_all_shards
    _ = [result.get() for result in results]  # noqa
  File "atram.py", line 147, in <listcomp>
    _ = [result.get() for result in results]  # noqa
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
sqlite3.OperationalError: no such table: aux.sra_blast_hits
```

But not with test 1, Phum.PHUM00340-PA.pep.fasta
```
(venv) molecularecology@molecular-ecology:~/Desktop/atram/aTRAM_12_14/aTRAM$ python atram.py -b testLib/tests -o tests2.atram -q Phum.PHUM003340-PA.pep.fasta
2017-12-21 16:31:16 INFO: aTRAM blast DB = "testLib/tests", query = "Phum.PHUM003340-PA.pep.fasta", iteration 1
2017-12-21 16:31:16 INFO: Blasting query against shards: iteration 1
```
Thank you!

**Comment by rafelafrance** [comment]
I think that this issue has been fixed. Would you please try this again with the latest release.

**Comment by juliema** [comment]
I am going to close this issue. If this is still occurring please reopen.

thanks!
