### ISSUE TITLE
sqlite errors

### ISSUE THREAD

**Issue by zjlahey** [juliema/aTRAM#216]
Hi,

I've been getting numerous I/O errors when using sqlite on our cluster. Any idea what's causing this? Output from atram_preprocessor.py is listed below.

2018-02-14 09:31:41 INFO: aTRAM version: 2.0.alpha.5
2018-02-14 09:31:41 INFO: atram_preprocessor.py --cpus 16 -b /home/lahey.18/aTRAM/databases/inostemma/inostemma_db --mixed-ends /home/lahey.18/aTRAM/databases/inostemma/inostemma_interleaved.fastq
2018-02-14 09:31:41 INFO: Loading "/home/lahey.18/aTRAM/databases/inostemma/inostemma_interleaved.fastq" into sqlite database
Traceback (most recent call last):
  File "atram_preprocessor.py", line 300, in <module>
    preprocess(ARGS)
  File "atram_preprocessor.py", line 34, in preprocess
    load_seqs(args, db_conn)
  File "atram_preprocessor.py", line 51, in load_seqs
    load_one_file(db_conn, file_name, arg, clamp)
  File "atram_preprocessor.py", line 82, in load_one_file
    db.insert_sequences_batch(db_conn, batch)
  File "/home/lahey.18/aTRAM/lib/db.py", line 126, in insert_sequences_batch
    db_conn.executemany(sql, batch)
sqlite3.OperationalError: disk I/O error

**Comment by zjlahey** [comment]
Setting the -b option to another disk worked. Thanks for clearing that up!
