### ISSUE TITLE
atram from docker image

### ISSUE THREAD

**Issue by kingcohn1** [juliema/aTRAM#218]
Hello again :) 

I've created a docker image with python3 spades3.11 and ncbi2.7 but having issues building the library:

```bash
root@1181ce0f152f:/# python3 /aTRAM/atram_preprocessor.py -l atram.log -b test2 --end-1 curate_CP6_r1.fasta --end-2 curate_CP6_r2.fasta 
2018-04-11 19:58:29 INFO: aTRAM version: 2.0.alpha.5
2018-04-11 19:58:29 INFO: /aTRAM/atram_preprocessor.py -l atram.log -b test2 --end-1 curate_CP6_r1.fasta --end-2 curate_CP6_r2.fasta
2018-04-11 19:58:29 INFO: Loading "curate_CP6_r1.fasta" into sqlite database
2018-04-11 19:58:35 INFO: Loading "curate_CP6_r2.fasta" into sqlite database
2018-04-11 19:58:41 INFO: Creating an index for the sequence table
2018-04-11 19:58:43 INFO: Assigning sequences to shards
2018-04-11 19:58:43 INFO: Making blast DBs
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/aTRAM/atram_preprocessor.py", line 139, in create_one_blast_shard
    blast.create_db(args['temp_dir'], fasta_path, shard)
  File "/aTRAM/lib/blast.py", line 22, in create_db
    log.subcommand(cmd, temp_dir)
  File "/aTRAM/lib/log.py", line 74, in subcommand
    stderr=log_output)
  File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'makeblastdb -dbtype nucl -in /tmp/atram_pcieq1ux/atram_preprocessor_001.fasta -out test2.001.blast' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/aTRAM/atram_preprocessor.py", line 300, in <module>
    preprocess(ARGS)
  File "/aTRAM/atram_preprocessor.py", line 41, in preprocess
    create_all_blast_shards(args, shard_list)
  File "/aTRAM/atram_preprocessor.py", line 120, in create_all_blast_shards
    _ = [result.get() for result in results]  # noqa
  File "/aTRAM/atram_preprocessor.py", line 120, in <listcomp>
    _ = [result.get() for result in results]  # noqa
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
subprocess.CalledProcessError: Command 'makeblastdb -dbtype nucl -in /tmp/atram_pcieq1ux/atram_preprocessor_001.fasta -out test2.001.blast' returned non-zero exit status 1.
```
this did not happen when I used the test data you shared with me earlier:

``` bash 
2018-04-11 19:55:17 INFO: aTRAM version: 2.0.alpha.5
2018-04-11 19:55:17 INFO: /aTRAM/atram_preprocessor.py -l atram.log -b test --end-1 ptgor_tiny_1.fasta --end-2 ptgor_tiny_2.fasta
2018-04-11 19:55:17 INFO: Loading "ptgor_tiny_1.fasta" into sqlite database
2018-04-11 19:55:17 INFO: Loading "ptgor_tiny_2.fasta" into sqlite database
2018-04-11 19:55:17 INFO: Creating an index for the sequence table
2018-04-11 19:55:17 INFO: Assigning sequences to shards
2018-04-11 19:55:17 INFO: Making blast DBs
2018-04-11 19:55:18 INFO: Finished making blast DBs
```

head of input files:
```bash
>HWI:D00256:413:C7N5GANXX:2:1101:1273:24711:N_1
CCTAAGATATGTTATTAGTTAAGAGTCAAATTATTTTGTGAATTTATGTAATAGATATAAGAAATTACGACTTAAGATATGGATATGATAATTTCAATGACAGGGTGCATCTCAGATTATGTTTAT
>HWI:D00256:413:C7N5GANXX:2:1101:1522:22521:N_1
GCAAGCATATTTATTGCAGCAACTTTGTTCTTCCCCGACAATTTCGATAACCTATTATCATTATTGCTATTATCATTACTAGCGTAGGATGCGCTGGTCAAATCCTATCTACCGAAATCCCGCTAC
>HWI:D00256:413:C7N5GANXX:2:1101:1722:22681:N_1
GACGGCTTTGCTGCTCTTCCATCCATCCGGGAATTCCCCTCTTCCTTTCATCCCATTCAGTACCTCCAGAATCGTGTCCGGCACGCACTCAATTCCAGCTTTGACCGTCTCAGTCCG
```

**Comment by juliema** [comment]
Will you send your input  files to  juliema@ufl.edu so I can test it?
