### ISSUE TITLE
atram blast not working whereas blast test works 

### ISSUE THREAD

**Issue by juliema** [juliema/aTRAM#238]
With this dataset  if we just build a blast database from the fasta file and blast we get hits. But if we build an atram library and blast through atram we get no hits. So there seems to be something about the libraries?

data on bear:
gspeedq32/atram_troubleshooting/dataset1_blast-work_atram_not

**Comment by juliema** [comment]
ok tested with atram 2.1  -- still getting an error. 

files on bear:  /srv/gspeedq32/atram_troubleshooting/dataset1_blast-work_atram_not

Reran the pre-prossesor 
python aTRAM/atram_preprocessor.py --end-1 Pgvar_1P.fasta --end-2 Pgvar_2P.fasta  -b pgvarfasta

Ran atram
python aTRAM/atram.py -b bgvarfasta -Q Ibbis_mt_genes.fasta -o fasta_test


using both fasta and fastq original files and then atram.py fails with 

Traceback (most recent call last):
  File "aTRAM/atram.py", line 216, in <module>
    assemble(ARGS)
  File "/srv/gspeedq32/atram_troubleshooting/dataset1_blast-work_atram_not/aTRAM/lib/core_atram.py", line 17, in assemble
    queries = split_queries(args)
  File "/srv/gspeedq32/atram_troubleshooting/dataset1_blast-work_atram_not/aTRAM/lib/core_atram.py", line 111, in split_queries
    path = join(args['temp_dir'], 'queries')
  File "/srv/gspeedq32/atram_2.0/atram_2.0/aTRAM/venv/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/srv/gspeedq32/atram_2.0/atram_2.0/aTRAM/venv/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
