### ISSUE TITLE
v2.3.0 --gzip option not working

### ISSUE THREAD

**Issue by HeatherKates** [juliema/aTRAM#284]
Hi guys,
I'm trying to use the --gzip option in v2.3.0 and get the following error message. (It runs fine if I remove the --gzip option and gunzip the files first.)

2020-03-25 16:23:08 INFO: ################################################################################
2020-03-25 16:23:08 INFO: aTRAM version: v2.3.0
2020-03-25 16:23:08 INFO: Python version: 3.6.5 (default, Apr 10 2018, 00:31:24) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
2020-03-25 16:23:08 INFO: aTRAM/atram_preprocessor.py -b P078_WA01 --end-1 ../1_Reads/Trimmed/P078_WA01_P1.fastq.gz --end-2 ../1_Reads/Trimmed/P078_WA01_P2.fastq.gz --gzip
2020-03-25 16:23:08 INFO: Loading "../1_Reads/Trimmed/P078_WA01_P1.fastq.gz" into sqlite database
2020-03-25 16:23:09 INFO: Loading "../1_Reads/Trimmed/P078_WA01_P2.fastq.gz" into sqlite database
2020-03-25 16:23:11 INFO: Creating an index for the sequence table
2020-03-25 16:23:11 INFO: Assigning sequences to shards
Traceback (most recent call last):
  File "aTRAM/atram_preprocessor.py", line 178, in <module>
    preprocess(ARGS)
  File "/ufrc/soltis/hkates/NITFIX/FMN_131001_P078/4_Assemble/aTRAM/lib/core_preprocessor.py", line 40, in preprocess
    shard_list = assign_seqs_to_shards(cxn, args['shard_count'])
  File "/ufrc/soltis/hkates/NITFIX/FMN_131001_P078/4_Assemble/aTRAM/lib/core_preprocessor.py", line 91, in assign_seqs_to_shards
    cuts = [db_preprocessor.get_shard_cut(cxn, offset) for offset in offsets]
  File "/ufrc/soltis/hkates/NITFIX/FMN_131001_P078/4_Assemble/aTRAM/lib/core_preprocessor.py", line 91, in <listcomp>
    cuts = [db_preprocessor.get_shard_cut(cxn, offset) for offset in offsets]
  File "/ufrc/soltis/hkates/NITFIX/FMN_131001_P078/4_Assemble/aTRAM/lib/db_preprocessor.py", line 72, in get_shard_cut
    cut = result.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

I can't attach gzip files here it seems, but if you need them I'll add to google drive. Thanks!

**Comment by rafelafrance** [comment]
You might need to use the `--fastq` option. atram is kinda dumb about file endings and when there's a .gz ending it doesn't see the "q" at the end of the file name.

**Comment by rafelafrance** [comment]
I should do better guessing on file types.

**Comment by HeatherKates** [comment]
Awesome, that works! Seems obvious now- I thought the --gzip option would override the --fastq option, but of course it is a fastq.gz file still different from fasta.gz. Thanks!

**Comment by rafelafrance** [comment]
Good.
I'm going to reopen this issue because I want to improve the file type guessing in atram. It's nothing you need to deal with.
