### ISSUE TITLE
'NoneType' object has no attribute 'debug'

### ISSUE THREAD

**Issue by tobiashofmann88** [juliema/aTRAM#290]
I'm trying to run the `atram_preprocessor.py` script on one of my samples. I get the following error. It seems like something goes wrong in the multiprocessing step, it seems that the object `LOGGER` is empty.
```
(aTRAM) Tobiass-MBP-2:seqcap_processor tobias$ bin/aTRAM-master/atram_preprocessor.py --blast-db=data/test/atram_library/sample_1061 --end-1=data/test/cleaned_reads/1061_clean/1061_clean-READ1.fastq --end-2=data/test/cleaned_reads/1061_clean/1061_clean-READ2.fastq
2020-06-16 12:30:30 INFO: ################################################################################
2020-06-16 12:30:30 INFO: aTRAM version: v2.3.1
2020-06-16 12:30:30 INFO: Python version: 3.8.3 (default, May 19 2020, 13:54:14) [Clang 10.0.0 ]
2020-06-16 12:30:30 INFO: bin/aTRAM-master/atram_preprocessor.py --blast-db=data/test/atram_library/sample_1061 --end-1=data/test/cleaned_reads/1061_clean/1061_clean-READ1.fastq --end-2=data/test/cleaned_reads/1061_clean/1061_clean-READ2.fastq
2020-06-16 12:30:30 INFO: Loading "data/test/cleaned_reads/1061_clean/1061_clean-READ1.fastq" into sqlite database
2020-06-16 12:30:32 INFO: Loading "data/test/cleaned_reads/1061_clean/1061_clean-READ2.fastq" into sqlite database
2020-06-16 12:30:34 INFO: Creating an index for the sequence table
2020-06-16 12:30:35 INFO: Making blast DBs
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/tobias/opt/anaconda3/envs/aTRAM/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/tobias/GitHub/seqcap_processor/bin/aTRAM-master/lib/core_preprocessor.py", line 120, in create_one_blast_shard
    blast.create_db(args['temp_dir'], fasta_path, shard)
  File "/Users/tobias/GitHub/seqcap_processor/bin/aTRAM-master/lib/blast.py", line 18, in create_db
    log.subcommand(cmd, temp_dir)
  File "/Users/tobias/GitHub/seqcap_processor/bin/aTRAM-master/lib/log.py", line 78, in subcommand
    LOGGER.debug(cmd)
AttributeError: 'NoneType' object has no attribute 'debug'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bin/aTRAM-master/atram_preprocessor.py", line 178, in <module>
    preprocess(ARGS)
  File "/Users/tobias/GitHub/seqcap_processor/bin/aTRAM-master/lib/core_preprocessor.py", line 37, in preprocess
    create_all_blast_shards(args, cxn, args['shard_count'])
  File "/Users/tobias/GitHub/seqcap_processor/bin/aTRAM-master/lib/core_preprocessor.py", line 98, in create_all_blast_shards
    all_results = [result.get() for result in results]
  File "/Users/tobias/GitHub/seqcap_processor/bin/aTRAM-master/lib/core_preprocessor.py", line 98, in <listcomp>
    all_results = [result.get() for result in results]
  File "/Users/tobias/opt/anaconda3/envs/aTRAM/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'debug'
```

**Comment by tobiashofmann88** [comment]
The output folder is created and contains the files `sample_1061.sqlite.db` and `sample_1061.atram_preprocessor.log`, the latter contains the following content:

**Comment by rafelafrance** [comment]
I have a patch for this. You will need to do a `git pull` to use it now. It should get you through your current analysis.

I'm working on a more permanent solution to handle what's going on with conda installs.
