### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by RominaSSBatista** [juliema/aTRAM#318]
Hi, thank you so much for this repository and all documentation related to aTRAM. It is very helpful. 

I am trying to run aTRAM preprocessor (HPC) and the output I am getting is as following: 

```
(   15569) 2022-12-12 16:38:45.740412 INFO : ################################################################################
(   15569) 2022-12-12 16:38:45.741501 INFO : aTRAM version: v2.4.4
(   15569) 2022-12-12 16:38:45.741802 INFO : Python version: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51) [GCC 9.4.0]
(   15569) 2022-12-12 16:38:45.742158 INFO : $aTRAM_PATH/atram_preprocessor.py -b $aTRAM_output/libraries/PD_1342 --cpus 10 -l $aTRAM_output/logs/PD_1342.preprocess.log -t /work/scratch-nopw/rominab/ --end-1 $DATA_PATH/PD_1342-READ1.1500000.fastq.gz --end-2 $DATA_PATH/PD_1342-READ2.1500000.fastq.gz --fastq --gzip
(   15569) 2022-12-12 16:38:46.087312 INFO : Creating an index for the sequence table
(   15569) 2022-12-12 16:38:46.113663 INFO : Assigning sequences to shards
Traceback (most recent call last):
  File "$aTRAM_PATH/atram_preprocessor.py", line 179, in <module>
    preprocess(ARGS)
  File "$aTRAM_PATH/aTRAM/lib/core_preprocessor.py", line 40, in preprocess
    shard_list = assign_seqs_to_shards(
  File "$aTRAM_PATH/aTRAM/lib/core_preprocessor.py", line 95, in assign_seqs_to_shards
    cuts = [db_preprocessor.get_shard_cut(cxn, offset) for offset in offsets]
  File "$aTRAM_PATH/aTRAM/lib/core_preprocessor.py", line 95, in <listcomp>
    cuts = [db_preprocessor.get_shard_cut(cxn, offset) for offset in offsets]
  File "$aTRAM_PATH/aTRAM/lib/db_preprocessor.py", line 91, in get_shard_cut
    cut = result.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
```

If I run: 

```
[rominab@sci2 aTRAM]$ ./util_check_requirements.py 
Python version.......................... OK
makeblastdb............................. OK
tblastn................................. OK
blastn.................................. OK
abyss................................... OK
trinity................................. OK
velvet.................................. OK
spades.................................. OK
bwa..................................... OK
bowtie2................................. OK
exonerate............................... OK
Traceback (most recent call last):
  File "./util_check_requirements.py", line 126, in <module>
    check_modules()
  File "./util_check_requirements.py", line 39, in check_modules
    installed_modules = parse_requirements(modules.decode('utf-8'))
  File "./util_check_requirements.py", line 29, in parse_requirements
    module = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Any advice will be appreciated. 
Thank you,
Romina

_Originally posted by @RominaSSBatista in https://github.com/juliema/aTRAM/issues/299#issuecomment-1346871543_

**Comment by RominaSSBatista** [comment]
I will close this issue because I fixed it. It was nothing related to aTRAM but my job settings on the HPC where I am running my analyses. Thank you.
