### ISSUE TITLE
atram_preprocessor.py taking a lot of time to load .fastq.gz files

### ISSUE THREAD

**Issue by RominaSSBatista** [juliema/aTRAM#319]
---
Hi, I am trying to build libraries from WGS to later recover UCEs, using aTRAM. When I am trying to run atram_preprocessor.py it is taking >12h to load a single .fastq.gz. One of our collaborators has done this step before using the same sample using v.2.3.3 and it was taking ~15min to load it. I am now using v.2.4.4 using the same resources to run the job and I am not managing to reproduce the same results. The same sample is taking more than 48 to process. Also the temporary directory is empty after many hours running. 

Just adding to this issue, I have run the ```./util_check_requirements.py``` script and I got the following:

```
Python version.......................... OK
makeblastdb............................. OK
tblastn................................. OK
blastn.................................. OK
abyss................................... OK
trinity................................. OK
velvet.................................. OK
spades.................................. OK
bwa..................................... OK
bowtie2................................. OK
exonerate............................... OK
Traceback (most recent call last):
  File "./util_check_requirements.py", line 126, in <module>
    check_modules()
  File "./util_check_requirements.py", line 39, in check_modules
    installed_modules = parse_requirements(modules.decode('utf-8'))
  File "./util_check_requirements.py", line 29, in parse_requirements
    module = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Here is the .sh I am using to run atram_preprocessor.py: 

```
#!/bin/bash

### run atram_preprocess for 1 sample to test the performance on JASMIN

#SBATCH --partition=par-single
#SBATCH --time=48:00:00
#SBATCH -N 1 
#SBATCH --cpus-per-task=10
#SBATCH --mem-per-cpu=4G
#SBATCH --job-name=atram_prep
#SBATCH -e /gws/nopw/j04/rotcotm/rominab/projects/3_alouatta/errors/atram_prep1_15012023J.err
#SBATCH -o /gws/nopw/j04/rotcotm/rominab/projects/3_alouatta/errors/atram_prep1_15012023J.out

module load jaspy
module load gcc
source $HOME/VirEnvPy3/bin/activate

aTRAM_dir="/home/users/rominab/softwares/aTRAM"

cd $aTRAM_dir

./atram_preprocessor.py \
--blast-db /gws/nopw/j04/rotcotm/rominab/projects/3_alouatta/aTRAM/libraries/PD0025_teste_15jan \
--cpus 10 \
--temp-dir /work/scratch-nopw/rominab \
--log-file /gws/nopw/j04/rotcotm/rominab/projects/3_alouatta/aTRAM/logs/PD0025_15012023J.preprocess.log \
--log-level debug \
--keep-temp-dir \
--end-1 /gws/nopw/j04/rotcotm/TrimReads/PD_0025/H5HHTDSXX_1_98UDI-idt-UMI_Trim_1.fastq.gz \
--end-1 /gws/nopw/j04/rotcotm/TrimReads/PD_0025/H5HHTDSXX_2_98UDI-idt-UMI_Trim_1.fastq.gz \
--end-2 /gws/nopw/j04/rotcotm/TrimReads/PD_0025/H5HHTDSXX_1_98UDI-idt-UMI_Trim_2.fastq.gz \
--end-2 /gws/nopw/j04/rotcotm/TrimReads/PD_0025/H5HHTDSXX_2_98UDI-idt-UMI_Trim_2.fastq.gz \
--fastq \
--gzip
```

And here is part of the log file: 

```
(   43158) 2023-01-16 12:58:32.735330 INFO : ################################################################################
(   43158) 2023-01-16 12:58:32.735600 INFO : aTRAM version: v2.4.4
(   43158) 2023-01-16 12:58:32.735692 INFO : Python version: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51) [GCC 9.4.0]
(   43158) 2023-01-16 12:58:32.735784 INFO : ./atram_preprocessor.py --blast-db /gws/nopw/j04/rotcotm/rominab/projects/3_alouatta/aTRAM/libraries/PD0025_teste_15jan --cpus 10 --temp-dir /work/scratch-nopw/rominab --log-file /gws/nopw/j04/rotcotm/rominab/projects/3_alouatta/aTRAM/logs/PD0025_15012023J.preprocess.log --log-level debug --keep-temp-dir --end-1 /gws/nopw/j04/rotcotm/TrimReads/PD_0025/H5HHTDSXX_1_98UDI-idt-UMI_Trim_1.fastq.gz --end-1 /gws/nopw/j04/rotcotm/TrimReads/PD_0025/H5HHTDSXX_2_98UDI-idt-UMI_Trim_1.fastq.gz --end-2 /gws/nopw/j04/rotcotm/TrimReads/PD_0025/H5HHTDSXX_1_98UDI-idt-UMI_Trim_2.fastq.gz --end-2 /gws/nopw/j04/rotcotm/TrimReads/PD_0025/H5HHTDSXX_2_98UDI-idt-UMI_Trim_2.fastq.gz --fastq --gzip
(   43158) 2023-01-16 12:58:32.963348 INFO : Loading "/gws/nopw/j04/rotcotm/TrimReads/PD_0025/H5HHTDSXX_1_98UDI-idt-UMI_Trim_1.fastq.gz" into sqlite database
(   43158) 2023-01-17 02:56:08.162563 INFO : Loading "/gws/nopw/j04/rotcotm/TrimReads/PD_0025/H5HHTDSXX_2_98UDI-idt-UMI_Trim_1.fastq.gz" into sqlite database
(   43158) 2023-01-17 14:14:29.313454 INFO : Loading "/gws/nopw/j04/rotcotm/TrimReads/PD_0025/H5HHTDSXX_1_98UDI-idt-UMI_Trim_2.fastq.gz" into sqlite database

```
Any advice or comment on this issue I will appreciate. 
Thank you, 
Romina

---

**Comment by RominaSSBatista** [comment]
The issue was solved by redirecting the libraries (--blast-db) to the parallel write scratch. 

```
./atram_preprocessor.py \
--blast-db /work/scratch-nopw/rominab/PD0025_teste_15jan \
--cpus 10 \
--temp-dir /work/scratch-nopw/rominab \
--log-file /gws/nopw/j04/rotcotm/rominab/projects/3_alouatta/aTRAM/logs/PD0025_15012023J.preprocess.log \
--log-level debug \
--keep-temp-dir \
--end-1 /gws/nopw/j04/rotcotm/TrimReads/PD_0025/H5HHTDSXX_1_98UDI-idt-UMI_Trim_1.fastq.gz \
--end-1 /gws/nopw/j04/rotcotm/TrimReads/PD_0025/H5HHTDSXX_2_98UDI-idt-UMI_Trim_1.fastq.gz \
--end-2 /gws/nopw/j04/rotcotm/TrimReads/PD_0025/H5HHTDSXX_1_98UDI-idt-UMI_Trim_2.fastq.gz \
--end-2 /gws/nopw/j04/rotcotm/TrimReads/PD_0025/H5HHTDSXX_2_98UDI-idt-UMI_Trim_2.fastq.gz \
--fastq \
--gzip
```

Big shout to @MareikeJaniak that gave me this advice and helped to solve it. :) 

Thank you, 
Romina
